### ISSUE TITLE
[REQUEST] Maintaining the user session

### ISSUE THREAD

**Issue by KeziahMoselle** [Founntain/osuplayer#108]
**Is your feature request related to a problem? Please describe.**
It is really frustrating to login each time I open the app.

**Describe the solution you'd like**
Keep the session for a longer duration

**Comment by Founntain** [comment]
This probably needs a rewrite and changes in the API. Because we simply don't want to store the users password or any kind of data.

Thats why we only remember the name and open the login window, so you just need to enter the password. 

We might check for a solution for it in the distant future. But for now we take more the solution of manually logging in. And lets be honest, if you don't (re)-start the play every x second/minutes it isn't that annoying. IMHO.
