### ISSUE TITLE
[BUG] Null song at top of list in playlist editor

### ISSUE THREAD

**Issue by klof44** [Founntain/osuplayer#157]
**Describe the bug**
Blank selectable option as second option in the playlist songs list in playlist editor. Attempting to remove this "null song" from the playlist will cause a crash.

**To Reproduce**
1. Open a playlist in playlist editor
2. Click on extra blank space between first and second song in the playlist songs section
3. Attempt to remove "null song" from playlist

**Expected behavior**
This extra blank option shouldn't be present in the first place.

**Screenshots**
![image](https://user-images.githubusercontent.com/59375588/203692095-f9f7b9c0-d59c-4e51-835f-d07fad8c80e1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2022.1013.0 (latest at the time of report)

**Comment by Founntain** [comment]
The extra blank line isn't an issue with the playlist editor, this is a song found inside your osu!.db. Usually mostly when these kind of blank songs popup, it's most likely that this is a corrupt song itself. A second reason could be that blank song got deleted in osu! but you have it still in your playlist. (Most likely)

I just tried it by giving one random song in my playlist an invalid checksum
> ![](https://7.founntain.dev/xmxiNTYA.png)

After that I notice that same issue you have:
> ![](https://7.founntain.dev/liqHYuw8.png)

It looks like that this song is on the second place (if not check what position it is) in your playlist. I would suggest checking the playlist file and remove the entry from their and start the player again and check if this solved the issue.
> You find the `playlist.json` file inside your `osu!player/data` directory.

However we still need a fix to be applied, that either those songs, that have an invalid checksum. Stop beeing blank and say (deleted song or whatever) and second make the player not crash. I'm currently investigating, but this can take a while because I'm currently @ work.
