### ISSUE TITLE
[Request] Player should jump to the current song in the list when it's progressing through the list, to keep track where it is and what's playing next

### ISSUE THREAD

**Issue by Umaimi** [Founntain/osuplayer#165]
Hihi, here's few things that popped up while I use the app. It'd be nice if we had:

- a way to jump to the current song that is playing or a highlight on the currently playing song (just so that people can see what will play after the current song)
- a way to pause/play/skip with media key or shortcut keys
-------------

Oh also, would it be possible to nudge the length of the song numbers a bit more to the left? It gets overlapped if the scroller thingy comes up.

(Might update in the future)

**Comment by Founntain** [comment]
- For the media keys we have to check about the global hotkeys stuff, but this should work. Because this got implemented with these https://github.com/Founntain/osuplayer/issues/53 and https://github.com/Founntain/osuplayer/pull/145
- About your "Way to Jump and preview" what do you mean with that? Can make a small example with a screenshot etc. etc.?
- And please show me where you kinda want the text to nudge a bit to the left and what exactly.

Would love to get these details, so we can evaluate these more for implementation for sure!

**Comment by Cesan** [comment]
1. This could be implemented maybe (depends on Avalonia's features), but just highlighting songs would then be a bit confusing if e.g. shuffle is turned on (2 of the 3 shuffle algorithms don't shuffle songs beforehand, so you won't be able to see the next ones), this would also be the case using playlist mode.
The best thing would be to have like a play queue where you can see this stuff, so we are independent of the other views and play modes.
2. The previous update included media key controls for windows, are you on a different platform than that?

**Comment by Founntain** [comment]
> 1. This could be implemented maybe (depends on Avalonia's features), but just highlighting songs would then be a bit confusing if e.g. shuffle is turned on (2 of the 3 shuffle algorithms don't shuffle songs beforehand, so you won't be able to see the next ones), this would also be the case using playlist mode.
>        The best thing would be to have like a play queue where you can see this stuff, so we are independent of the other views and play modes.
> 
>     2. The previous update included media key controls for windows, are you on a different platform than that?

I agree with the these

**Comment by Umaimi** [comment]
1. True I didn't think of shuffle mode since I never use it lol;; But uhh, I'm strictly suggesting this function for the "search song list" page (or whatever the "Magnifying glass" page is called) because I always have that page on. 
To clarify what I wanted, let me give a context:
When I open the app, I go right away to the song list page and I have the habit to immediately scroll to the current song that is playing so I know what will be playing next. I have the setting of "continue where you last left off" so when I want to know what's next, I have to manually pay attention to the alphabetical order to find the song in the list, as there are no indication (a highlight or anything) or a way to "jump" to the current playing song. I suppose my main goal here is less on the "knowing what's next" and more to "seeing where this current song is in the list".
As for "a way to quickly know what is playing/what will be played next", I'm sure there's multiple way of making it. One of them could be like a button that lets you jump to what is playing right now. 
At the end of the day, I'm not sure how useful this function is because it's just more of my OCD kinda thing lolol.

2. I wasn't aware the media key was a thing now. Yes, I am on Win 10. I'm trying right now to press my media key but nothing is happening? And I'm sure I have the latest version because just updated it last night.

3. As the for the song length nudge, here's screenshots on my side:

-Fullscreen-
![fullscreen 1](https://user-images.githubusercontent.com/89648776/206060323-4f9c37c2-9160-4053-bd6f-af9c5c8a9e1a.png)
![fullscreen 2](https://user-images.githubusercontent.com/89648776/206060338-2ee4b526-e729-45af-8233-15a13e694ad6.png)

-Windowed-
![windowed 1](https://user-images.githubusercontent.com/89648776/206060372-303cc7d3-3261-46f5-9bb5-07aa970b0ebd.png)
![windowed 2](https://user-images.githubusercontent.com/89648776/206060379-132cad42-36a8-47fc-9878-88e15a45069d.png)

**Comment by Founntain** [comment]
1. That's actually not that kind of a stupid Idea and secondly the old osu!player even had this feature to jump to the song that is playing right now. We can definitly do something like that. But I think this will only make sense for the home view. The search view is to dynamic. But I would love to hear what @Cesan has to say to that.
2. We have to check that why it isn't working. 
3. I see your problem with the scrollbar and it's definitly a bug.
4. Should be a thing if the media keys would work, because this thingy with the title and cover got implemented with #145 
> The reason why you don't see it because the media keys arn't working in the first place.

I made some additional Issues to keep track of those stuff you mentioned.
