### ISSUE TITLE
[REQUEST] I want to request some features

### ISSUE THREAD

**Issue by AyanoKiru** [Founntain/osuplayer#210]
1.In the page that does nothing, you can use that to show lyrics like MusicBee, foobar2000,...
(The page that does nothing)
![image](https://github.com/Founntain/osuplayer/assets/66897456/3ec30b97-4765-4ffa-a3dc-c3b27b51b1d0)
(Example)
![image](https://github.com/Founntain/osuplayer/assets/66897456/fcd00d04-bcb9-474e-ab7e-86125f4132ef)
The suggestion to make this possible is to allow the user to paste lyrics from a certain source into the music file (embed lyric) or save it locally in the osu!player folder. (Support sync lyric if possible)
(Example)
![image](https://github.com/Founntain/osuplayer/assets/66897456/1c394118-2e1e-46de-9f32-addd27083576)
2. Add a function to help users see the metadata of the song
It can be simple or complex
The suggestion to make this possible is add a line 'Song Info' on right click or use "the page that does nothing"
3. Add history
4. Plugin support (.dll support)

**Comment by Founntain** [comment]
1. I don't see any sense, why we should support it. As A it generates a lot of overhead for us to implement (sync) and B osu! songs don't have lyrics in general, so I don't see why any user would look up the lyrics and paste them one by one.
2. If you mean the metadata of a osu! song, and just the info that is stored inside the Beatmap. Yes we could do that. But on the other hand I'm more thinking why this is needed and should be implemented. In the end this is a music player. Most of the metadata inside that **.osu** file is just stuff for the Beatmap. Timing points etc. etc. there isn't that much meta data for the song itself
3. If you mean a play history, then yes why not. this makes sense to implement.
4. Why? There is like no reason in the world we need that. First we have to write a framework that makes it even possible to create said plugins and load them into our app. Meanwhile you could implement the plugin itself into the player as a feature and make it a feature itself instead of a plugin. There is a reason why we are open source. If a person has an idea and wants to implement it as a feature there is no way of us stopping them. It's all mentioned in the Contributing section on the Read Me.

> *also I want to mention that the nothing page is already reserved for the beatmap page, when it's done it will replace that view*
