### ISSUE TITLE
[BUG] Player crashes when trying to import songs

### ISSUE THREAD

**Issue by KNN-07** [Founntain/osuplayer#263]
**Describe the bug**
osuplayer crashed

**To Reproduce**
1. Go to settings
2. Click on import song
3. Choose osu!.db
4. Open
5. Crashed

**Expected behavior**
It should import the song

**Screenshots**
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 (build 22631.2861)

**Additional context**
The osu! song folder of mine is changed to a different drive by editing the osu!.{user}.cfg file
Bug Report: [20231219_143248.txt](https://github.com/Founntain/osuplayer/files/13716819/20231219_143248.txt)

**Comment by Founntain** [comment]
If you are saying, you changed your osu songs folder to a different drive using the config, we can't help you with that either you use have the songs in the expected directory or use the second recommend way using symlinks as those are working perfectly fine and should be used for that.

**Comment by Founntain** [comment]
And please give your issues a title and not an empty one

**Comment by KNN-07** [comment]
> And please give your issues a title and not an empty one

Oops i forgot 🙃

**Comment by Founntain** [comment]
However please use symbolic links if you want you songs to be on a different drive, folder or wherever you want and don't alter the osu!.username.cfg nobody does or should do that. Also the error that came up had nothing todo with your folder but with your osu!.db as it couldn't even open your osu!.db for whatever reason. (It might be because of the config, but I doubt that) Please check for symlinks or try it with the default songs folder if the issue persist. 

As I'm 100% sure that if it would be a cause of the wrong different osu! path we would get a different error on a completely different place and not when trying to open the osu!.db

So also check, osu!player has enough permissions to be able to read other files.

If you never used symlinks here is a guide to help you with that.
https://www.reddit.com/r/osugame/comments/u42n4j/psa_you_can_put_your_songs_folder_into_another/
