### ISSUE TITLE
[REQUEST] Media Overlay

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#53]
This issue was taken from the [osu!player plus issue list](https://github.com/Founntain/osuplayer-issues/issues/31)

**Original Issue below**

I wanna be able to see what is playing without having to alt tab to the music player window but currently whenever I press the keyboard press/play button, no media overlay appears so I can't tell.

Usually on Spotify it would look like this
![image](https://user-images.githubusercontent.com/89648776/153667375-5a959e30-3778-4c8a-a5eb-cc927e1053e5.png)

**Comment by Cesan** [comment]
This is currently hardly possible, because this is a Windows 10 API contract thing for UWP apps which works over SystemMediaTransportControls and requires Windows/UWP specific stuff. As we use Avalonia for our app I don't know if this is possible at all. So for now give this a very low priority before looking into it.
